# Arquivo: .streamlit/secrets.toml

[db_credentials]
driver = "ODBC Driver 17 for SQL Server"
server = "SEU_SERVIDOR_IP_OU_NOME"
database = "DBDMhealth_prod"
username = "SEU_USUARIO"
password = "SUA_SENHA"